config/routes.rb
Rails.application.routes.draw do

  resources :labels, only: [:show]

  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments,  only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new] do
        resources :posts, only: [:create]
      end
      resources :posts, only: [:update, :destroy]
    end
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  scope :visible_to, -> (user) { user ? all : publicly_viewable }

  scope :publicly_viewable,   -> { where(public: true) }
  scope :privately_viewable,  -> { where(public: false) }
end

app/controllers/api/v1/topics_controller.rb
class Api::V1::TopicsController < Api::V1::BaseController
  before_filter :authenticate_user, except: [:index, :show]
  before_filter :authorize_user, except: [:index, :show]

  def index
    topics = Topic.all
    render json: topics.to_json, status: 200
  end

  def show
    topic = Topic.find(params[:id])
    render json: topic.to_json, status: 200
  end

  def update
    topic = Topic.find(params[:id])

    if topic.update_attributes(topic_params)
      render json: topic.to_json, status: 200
    else
      render json: {error: "Topic update failed", status: 400}, status: 400
    end
  end

  def create
    topic = Topic.new(topic_params)

    if topic.valid?
      topic.save!
      render json: topic.to_json, status: 201
    else
      render json: {error: "Topic is invalid", status: 400}, status: 400
    end
  end

  def destroy
    topic = Topic.find(params[:id])

    if topic.destroy
      render json: {message: "Topic destroyed", status: 200}, status: 200
    else
      render json: {error: "Topic destroy failed", status: 400}, status: 400
    end
  end


  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :require_sign_in, except: [:index, :show]
  before_action :authorize_user, except: [:index, :show]

  def index
    @topics = Topic.visible_to(current_user)
  end

  def show
    @topic = Topic.find(params[:id])

    unless @topic.public || current_user
      flash[:error] = "You must be signed in to view private topics."
      redirect_to new_session_path
    end
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      @topic.labels = Label.update_labels(params[:topic][:labels])
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash[:error] = "There was an error saving the topic. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.assign_attributes(topic_params)

    if @topic.save
      @topic.labels = Label.update_labels(params[:topic][:labels])
      redirect_to @topic, notice: "Topic was updated successfully."
    else
      flash[:error] = "There was an error updating the topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.name}\" was deleted successfully"
      redirect_to action: :index
    else
      flash[:error] = "There was an error deleting the topic."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end

  def authorize_user
    unless current_user.admin?
      flash[:error] = "You must be an admin to do that."
      redirect_to topics_path
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_to_edit_topics?
    current_user && (current_user.mod? || current_user.admin?)
  end

  def user_is_authorized_to_create_and_delete_topics?
    current_user && current_user.admin?
  end
end

app/views/topics/_form.html.erb
<%= form_for topic do |f| %>
  <% if topic.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(topic.errors.count, "error") %>.</h4>
      <ul>
        <% topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(topic.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter topic name" %>
  <% end %>
  <%= form_group_tag(topic.errors[:description]) do %>
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", placeholder: "Enter topic description" %>
  <% end %>
  <div class="form-group">
    <%= f.label :public, class: "checkbox" do %>
      <%= f.check_box :public %> Public topic
    <% end %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <p><%= link_to topic.name, topic %></p>
    </h4>
    <small>
      <%= topic.description %>
    </small>
  </div>
</div>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-4">
    <h4>Guidelines for Topics</h4>
    <ul>
      <li>Don't name the topic. Understand it, deep down in your heart, and the topic will name itself.</li>
      <li>Topics should be topical. No one cares about anything that happened before 5 minutes ago.</li>
      <li>Ignore the above rule. All topics should be <em>StarTropics</em>.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", placeholder: "Enter new topic name" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", placeholder: "Enter new topic description" %>
      </div>
      <div class="form-group">
        <%= render partial: 'labels/form', locals: { f: f, labels: @topic.labels } %>
      </div>
      <div class="form-group">
        <%= f.label :public, class: "checkbox" do %>
          <%= f.check_box :public %> Public topic
        <% end %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<h1>All Topics</h1>

<div class="row">
  <div class="col-md-8">
    <%= render @topics %>
  </div>
  <% if user_is_authorized_for_topics? %>
    <div class="col-md-4">
      <%= link_to "New Topic", new_topic_path, class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <h4>Guidelines for Topics</h4>
    <ul>
      <li>Don't name the topic. Understand it, deep down in your heart, and the topic will name itself.</li>
      <li>Topics should be topical. No one cares about anything that happened before 5 minutes ago.</li>
      <li>Ignore the above rule. All topics should be <em>StarTropics</em>.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", placeholder: "Enter topic name" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", placeholder: "Enter topic description" %>
      </div>
      <div class="form-group">
        <%= render partial: 'labels/form', locals: { f: f, labels: @topic.labels } %>
      </div>
      <div class="form-group">
        <%= f.label :public, class: "checkbox" do %>
          Public topic <%= f.check_box :public, style: "margin-left: 10px;" %>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% if user_is_authorized_for_topics? %>
  <%= link_to "Edit Topic", edit_topic_path, class: "btn btn-success" %>
  <%= link_to "Delete Topic", @topic, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete this topic?" } %>
<% end %>

<div class="row">
  <div class="col-md-8">
    <p class="lead">
      <%= render partial: "labels/list", locals: { labels: @topic.labels } %>
      <br>
      <%= @topic.description %>
    </p>
    <% @topic.posts.each do |post| %>
      <div class="media">
        <%= render partial: 'votes/voter', locals: { post: post } %>
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to post.title, topic_post_path(@topic, post) %>
            <%= render partial: "labels/list", locals: { labels: post.labels } %>
          </h4>
          <small>
            submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
            <%= post.comments.count %> Comments
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <% if current_user %>
    <div class="col-md-4">
      <%= link_to "New Post", new_topic_post_path(@topic), class: "btn btn-success" %>
    </div>
  <% end %>
</div>