config/routes.rb
Rails.application.routes.draw do

  resources :labels, only: [:show]

  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments,  only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new] do
        resources :posts, only: [:create]
      end
      resources :posts, only: [:update, :destroy]
    end
  end
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true

  after_create :send_favorite_emails

  default_scope { order('updated_at ASC') }


  private

  def send_favorite_emails
    post.favorites.each do |favorite|
      FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
    end
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/label.rb
class Label < ActiveRecord::Base
  belongs_to :labelable, polymorphic: true
  has_many :labelings
  has_many :topics, through: :labelings, source: :labelable, source_type: :Topic
  has_many :posts, through: :labelings, source: :labelable, source_type: :Post

  def self.update_labels(label_string)
    return Label.none if label_string.blank?

    label_string.split(',').map do |label|
      Label.find_or_create_by(name: label.strip)
    end
  end
end

app/models/labeling.rb
class Labeling < ActiveRecord::Base
  belongs_to :labelable, polymorphic: true
  belongs_to :label
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings
  has_many :favorites, dependent: :destroy

  # Scopes
  default_scope { order('rank DESC') }

  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

  def self.order_by_title
    reorder('title ASC')
  end

  def self.reverse_by_title
    reorder('title DESC')
  end

  # Validations
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true


  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  # enum severity: [ :PG, :PG13, :R ]
  enum severity: { G: 3, PG: 0, PG13: 1, R: 2, X: 4 }
  belongs_to :topic
  belongs_to :post

  # def self.update_rating(rating_string)
  #
  # end
end

app/models/sponsored_post.rb
class SponsoredPost < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  scope :visible_to, -> (user) { user ? all : publicly_viewable }

  scope :publicly_viewable,   -> { where(public: true) }
  scope :privately_viewable,  -> { where(public: false) }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  before_save { self.email = email.downcase }
  before_save { self.role ||= :member }

  before_create :generate_auth_token

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, length: { minimum: 1, maximum: 100 }, presence: true

  validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 100 },
            format: { with: EMAIL_REGEX }

  has_secure_password

  enum role: [:member, :admin]

  def favorite_for(post)
    favorites.where(post_id: post.id).first
  end

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def generate_auth_token
    loop do
      self.auth_token = SecureRandom.base64(64)
      break unless User.find_by(auth_token: auth_token)
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

  private

  def update_post
    post.update_rank
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  before_filter :authenticate_user
  before_filter :authorize_user

  def show
    user = User.find(params[:id])
    render json: user.to_json, status: 200
  end

  def index
    users = User.all
    render json: users.to_json, status: 200
  end

  def update
    user = User.find(params[:id])

    if user.update_attributes(user_params)
      render json: user.to_json, status: 200
    else
      render json: {error: "User update failed", status: 400}, status: 400
    end
  end

  def create
    user = User.new(user_params)

    if user.valid?
      user.save!
      render json: user.to_json, status: 201
    else
      render json: {error: "User is invalid", status: 400}, status: 400
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name                  = params[:user][:name]
    @user.email                 = params[:user][:email]
    @user.password              = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      flash[:notice] = "Welcome to Bloccit, #{@user.name}!"
      create_session(@user)
      redirect_to root_path
    else
      flash[:error] = "There was an error creating your account. Please try again."
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.visible_to(current_user)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment?(comment)
    current_user && (current_user == comment.user || current_user.admin?)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/labels_helper.rb
module LabelsHelper

  def labels_to_buttons(labels)
    raw labels.map { |l| link_to l.name, label_path(id: l.id), class: "btn-xs btn-primary" }.join(' ')
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create_session(user)
    session[:user_id] = user.id
  end

  def destroy_session(user)
    session[:user_id] = nil
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_to_edit_topics?
    current_user && (current_user.mod? || current_user.admin?)
  end

  def user_is_authorized_to_create_and_delete_topics?
    current_user && current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def user_has_posts?(user)
    if user.posts.count > 0
      return true
    else
      return false
    end
  end

  def user_has_comments?(user)
    if user.comments.count > 0
      return true
    else
      return false
    end
  end

  def user_has_favorites?(user)
    if user.favorites.count > 0
      return true
    else
      return false
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/_favorite.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to favorite.post.title, topic_post_path(favorite.post.topic, favorite.post) %>
    </h4>
    <small>
      <%= avatar_url = favorite.post.user.avatar_url(28) %>
      <% if avatar_url %>
        <div class="media-right">
          <% image_tag avatar_url, class: "media-object" %>
        </div>
      <% end %>
      <div class="media-right">
        <%= pluralize(favorite.post.votes.count, 'vote') %>
        <%= pluralize(favorite.post.comments.count, 'comment') %>
      </div>
    </small>
  </div>
</div>

app/views/users/confirm.html.erb
<div class="row">
  <div class="col-md-8">
    <h2>Sign Up Confirmation</h2>
    <h3>Are you sure these values are correct?</h3>
  </div>
  <div class="col-md-4">
    <h3>Email: <%= @user.email %></h3>
    <h3>Name: <%= @user.name %></h3>
    <br>
    <%= button_to "Yes", {controller: "users", action: "create", params: params}, class: "btn btn-success" %>
    <%= link_to "No", new_user_path, class: "btn btn-danger" %>
  </div>
</div>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<div class="row">
  <div class="col-md-8">
    <%= form_for @user, :url => { :action => :confirm } do |f| %>
      <!-- Report Errors -->
      <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <!-- Submission Form -->
      <%= form_group_tag(@user.errors[:name]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Enter name" %>
      <% end %>
      <%= form_group_tag(@user.errors[:email]) do %>
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control", placeholder: "Enter email address" %>
      <% end %>
      <%= form_group_tag(@user.errors[:password]) do %>
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
      <% end %>
      <%= form_group_tag(@user.errors[:password_confirmation]) do %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password confirmation" %>
      <% end %>
      <div class="form-group">
        <%= f.submit "Sign up", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="media">
      <br>
      <% avatar_url = @user.avatar_url(128) %>
      <% if avatar_url %>
        <div class="media-left">
          <%= image_tag avatar_url, class: "media-object" %>
        </div>
      <% end %>
      <div class="media-body">
        <h2 class="media-heading"><%= @user.name %></h2>
        <small>
          <%= pluralize(@user.posts.count, 'post') %>,
          <div class='js-comments-count'><%= pluralize(@user.comments.count, 'comment') %></div>
        </small>
      </div>
    </div>
  </div>
</div>

<h2>Posts</h2>
<%= render @user.posts %>

<h2>Comments</h2>
<%= render @user.comments %>