config/routes.rb
Rails.application.routes.draw do

  resources :labels, only: [:show]

  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments,  only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new] do
        resources :posts, only: [:create]
      end
      resources :posts, only: [:update, :destroy]
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings
  has_many :favorites, dependent: :destroy

  # Scopes
  default_scope { order('rank DESC') }

  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

  def self.order_by_title
    reorder('title ASC')
  end

  def self.reverse_by_title
    reorder('title DESC')
  end

  # Validations
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true


  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::BaseController
  before_filter :authenticate_user
  before_filter :authorize_user

  def create
    topic = Topic.find(params[:topic_id])
    post = topic.posts.new(post_params)
    post.user = @current_user

    if post.valid?
      post.save!
      render json: post.to_json, status: 201
    else
      render json: {error: "Post is invalid", status: 400}, status: 400
    end
  end

  def update
    post = Post.find(params[:id])

    if post.update_attributes(post_params)
      render json: post.to_json, status: 200
    else
      render json: {error: "Post update failed", status: 400}, status: 400
    end
  end

  def destroy
    post = Post.find(params[:id])

    if post.destroy
      render json: {message: "Post destroyed", status: 200}, status: 200
    else
      render json: {error: "Post destroy failed", status: 400}, status: 400
    end
  end


  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_sign_in, except: :show
  before_action :authorize_user, except: [:show, :new, :create]

  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(post_params)
    @post.user = current_user
    @post.build_rating(severity: params[:post][:rating])

    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)

    if @post.save
      flash[:notice] = "Post was updated."
      redirect_to [@post.topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @post.topic
    else
      flash[:error] = "There was an error deleting the post."
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorize_user
    post = Post.find(params[:id])
    unless current_user == post.user || current_user.admin?
      flash[:error] = "You must be an admin to do that."
      redirect_to [post.topic, post]
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter post title" %>
  <% end %>
  <%= form_group_tag(post.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: "form-control", placeholder: "Enter post body" %>
  <% end %>
  <%= form_group_tag(post.errors[:rating]) do %>
    <%= f.label :rating %>
    <%= f.select :rating, options_for_select(Rating.severities.keys, post.rating.try(:severity) || :G) %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="media">
  <%= render partial: 'votes/voter', locals: { post: post } %>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to post.title, topic_post_path(post.topic, post) %>
      <%= render partial: 'labels/list', locals: { labels: post.labels } %>
    </h4>
    <small>
      submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
      <%= post.comments.count %> Comments
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>All posts must be in the form of a haiku (or a Spenserian sonnet as dictated by length)</li>
      <li>All posts must contain a reference to the failed NBC sitcom <em>Go Fish</em></li>
      <li>Posts may not paraphrase the works of Ludwig Prinn or leave muddy footprints on the carpet</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-4">
    <h4>Guidelines for Posting</h4>
    <ul>
      <li>All posts must be in the form of a haiku (or a Spenserian sonnet as dictated by length)</li>
      <li>All posts must contain a reference to the failed NBC sitcom <em>Go Fish</em></li>
      <li>Posts may not paraphrase the works of Ludwig Prinn or leave muddy footprints on the carpet</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
  </div>
</div>

app/views/posts/show.html.erb
<div>
  <%= render partial: 'votes/voter', locals: { post: @post } %>
  <h1>
    <%= @post.title %>
    <small>
      submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %>
    </small>
  </h1>
</div>
<div class="row">
  <div class="col-md-8">
    <%= render partial: "labels/list", locals: { labels: @post.labels } %>
    <br>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-8">
    <p><%= @post.body %></p>
    <div>
      <h3>Comments</h3>
      <div class='js-comments'>
        <%= render @post.comments %>
      </div>
    </div>
    <% if current_user %>
      <div class='new-comment'>
        <%= render 'comments/form', comment: Comment.new, post: @post %>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <% if user_is_authorized_for_post?(@post) %>
      <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: "btn btn-success pull-left" %>
      <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: "btn btn-danger pull-left", data: {confirm: "Are you sure you want to delete this post?"} %>
    <% end %>
  </div><br>
  <div class="col-md-4">
    <h3>
      <%= pluralize(@post.points, 'point') %><br>
      <div>
        <small>
          <%= pluralize(@post.up_votes, 'up vote') %>,
          <%= pluralize(@post.down_votes, 'down vote') %>
        </small>
      </div>
    </h3>
    <% if current_user %>
      <%= render partial: 'favorites/favorite', locals: { post: @post } %>
    <% end %>
  </div>
</div>